# Generated by Django 5.0.4 on 2024-04-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('NEBULA', 'Nebula'), ('STAR', 'Star'), ('GALAXY', 'Galaxy'), ('planet', 'Planet')], default='', max_length=50),
        ),
    ]
