# Generated by Django 5.0.4 on 2024-04-12 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0003_photo_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
