# Generated by Django 5.0.4 on 2024-04-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0004_photo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photoPath',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
